[package]
name = "hello-wry"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tao = "0.29.1"
wry = "0.42.0"
